FROM fedora:latest
RUN dnf update -y && dnf install which git screen pinentry make gcc procps-ng -y
RUN dnf install -y curl jq nodejs
RUN dnf install -y nano
COPY . /root/arching-kaos-tools
RUN bash -c 'cd /root/arching-kaos-tools && /root/arching-kaos-tools/install.sh'
RUN git config --global user.email "kaos@kaos.kaos"
RUN git config --global user.name "kaos"
RUN git config --global init.defaultBranch master
EXPOSE 4001/tcp
EXPOSE 5001/tcp
EXPOSE 8080/tcp
EXPOSE 8610/tcp
ENTRYPOINT ["/root/.arching-kaos/bin/ak-startup", "--start", "--podman"]


