FROM fedora:latest
RUN sudo dnf update -y && sudo dnf install wget which git screen pinentry -y 
COPY . /root/arching-kaos-tools
RUN bash -c 'cd /root/arching-kaos-tools && /root/arching-kaos-tools/install.sh'
RUN git config --global user.email "test@test.test"
RUN git config --global user.name "test"
RUN git config --global init.defaultBranch master
EXPOSE 4001/tcp
EXPOSE 5001/tcp
EXPOSE 8080/tcp
ENTRYPOINT ["tail","-f","/root/.arching-kaos/logs"]


