#!/usr/bin/env bash
###
### arching-kaos-tools
### Tools to interact and build an Arching Kaos Infochain
### Copyright (C) 2021 - 2025  kaotisk
###
### This program is free software: you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program.  If not, see <http://www.gnu.org/licenses/>.
###
source $AK_LIBDIR/_ak_log
source $AK_LIBDIR/_ak_network_ipfs
source $AK_LIBDIR/_ak_network_cjdns
source $AK_LIBDIR/_ak_network_yggdrasil
source $AK_LIBDIR/_ak_network_stellar
source $AK_LIBDIR/_ak_network_incoming

function _ak_network_scan(){
    if [ ! -z $1 ] && [ -n "$1" ]
    then
        case $1 in
            stellar) _ak_network_stellar_scan; exit;;
            ipfs) _ak_network_ipfs_scan; exit;;
            cjdns) shift; _ak_network_cjdns_scan $1; exit;;
            yggdrasil) shift; _ak_network_yggdrasil_scan $1; exit;;
            incoming) shift; _ak_network_incoming_scan; exit;;
            * ) _ak_log_error "Unknown network $1";exit 1;;
        esac
    else
        _ak_network_stellar_scan
        _ak_network_ipfs_scan
        _ak_network_cjdns_scan
        _ak_network_yggdrasil_scan
    fi
}

function _ak_network_show_peers(){
    if [ ! -z $1 ] && [ -n "$1" ]
    then
        case $1 in
            stellar) _ak_network_stellar_show_peers; exit;;
            cjdns) _ak_network_cjdns_show_peers; exit;;
            ipfs) _ak_network_ipfs_show_peers; exit;;
            yggdrasil) _ak_network_yggdrasil_show_peers; exit;;
            * ) _ak_log_error "Unknown network $1";exit 1;;
        esac
    else
        (_ak_network_stellar_show_peers; _ak_network_cjdns_show_peers; _ak_network_yggdrasil_show_peers; _ak_network_ipfs_show_peers) | \
            jq -j | \
            sed -e 's/]\[/,/g' | \
            jq
    fi
}

function _ak_network_connect(){
    if [ ! -z $1 ] && [ -n "$1" ]
    then
        case $1 in
            cjdns) _ak_network_cjdns_connect_bootstrap; exit;;
            ipfs) _ak_network_ipfs_connect_bootstrap; exit;;
            * ) _ak_log_error "Unknown network $1";exit 1;;
        esac
    else
        _ak_network_cjdns_connect_bootstrap
        _ak_network_ipfs_connect_bootstrap
    fi
}
