#!/usr/bin/env bash
source $AK_LIBDIR/_ak_node

_ak_config_show(){
    # We will be using our public key also to put it in the block later
    KEY="self.pub"
    ak-gpg --export-key-self-to-file
    _ak_log_debug "$KEY"
    GPG_PUB_KEY=$(_ak_ipfs_add $KEY)
    rm $KEY
    profile="$(ak-profile -l)"

    echo '
{
    "profile":'$profile',
    "genesis":"'$(cat $AK_WORKDIR/config/zgenesis)'",
    "gpg":"'$GPG_PUB_KEY'",
    "zchain":"'$(cat $AK_WORKDIR/config/zchain)'",
    "zlatest":"'$(ak zchain --get-latest)'"
}'| jq;
}

_ak_config_publish(){
    _ak_config_show | jq -c -M > tmpfile
    ipfs_hash="$(_ak_ipfs_add tmpfile)"
    _ak_ipfs_config_publish $ipfs_hash
    if [ $? != 0 ]
    then
        echo -e "\033[0;34mError on publishing\033[0;0m\nYour information:\n"
        cat tmpfile
        exit 1
    fi
    rm tmpfile
}

_ak_config_published(){
    _ak_ipfs_cat $(_ak_node_info_ipfs_hash) | jq
}

