#!/bin/bash

_ak_fm_remove_line_from_file(){
    tempfile="$(_ak_make_temp_file)"
    if [ ! -f "$2" ]
    then
        _ak_log_error "$2 does not exist"
        exit 1
    fi
    grep "$1" "$2" > /dev/null 2>&1
    if [ $? -ne 0 ]
        _ak_log_error "Could not find line: $1 in $2"
        exit 1
    fi
    grep -v "$1" "$2" > $tempfile
    cat $tempfile > $2
    rm $tempfile
}

_ak_fm_sort_uniq_file(){
    if [ ! -f "$1" ]
    then
        _ak_log_info "No file to process"
    else
        _ak_log_info "Sorting $1..."
        tempfile="$(_ak_make_temp_file)"
        cat "$1" | sort | uniq > $tempfile
        cat $tempfile > $1
        rm $tempfile
        _ak_log_info "Sorting $1... Done!"
    fi
}
