#!/bin/bash
source $AK_LIBDIR/_ak_ipfs

# Resolves the IPNS key "ak-config" to its current IPFS value
# Return IPFS CIDv0 without /ipfs/ prefix
_ak_node_info_ipfs_hash(){
    _ak_ipfs_name_resolve /ipns/$(_ak_node_info_ipns_key) | sed -e 's/\/ipfs\///'
}

# Finds ak-config ipns key
# Returns IPNS key
_ak_node_info_ipns_key(){
    _ak_ipfs_key_list_full | grep ak-config | awk '{print $1}'
}
