#!/usr/bin/env bash
###
### arching-kaos-tools
### Tools to interact and build an Arching Kaos Infochain
### Copyright (C) 2021 - 2025  kaotisk
###
### This program is free software: you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program.  If not, see <http://www.gnu.org/licenses/>.
###

source $AK_LIBDIR/_ak_log

function _ak_datetime_unix(){
    date -u +%s | tr -d '\n'
}

function _ak_datetime_unix_nanosecs(){
    date -u +%s.%N | tr -d '\n'
}

function _ak_datetime_human(){
    date -u +%Y%m%d_%H%M%S
}

function _ak_datetime_human_date_only(){
    date -u +%Y%m%d
}

function _ak_datetime_human_date_only_yesterday(){
    date --date=yesterday -u +%Y%m%d 2>/dev/null || date -v -1d -u +%Y%m%d 2>/dev/null
}

function _ak_datetime_unix_to_human(){
    if [ ! -z $1 ] && [ -n "$1" ] && [ "$(echo $1 | sed -e 's/[0-9]\{10\}//g')" == "" ]
    then
        date --date=@$1 +%Y%m%d_%H%M%S 2>/dev/null || date -r $1 +%Y%m%d_%H%M%S 2>/dev/null
    fi
}

_ak_log_debug "_ak_datetime loaded $(caller)"
