#!/bin/bash

source $AK_LIBDIR/_ak_newline

description(){
  full_title="$(printf '%s - %s' "$PROGRAM" "$descriptionString")"
  delimiter_count=`echo -n $full_title | wc -c`
  printf '%s' "$full_title"
  new_line
  while [ $delimiter_count -gt 0 ]
  do
    printf '='
    delimiter_count=$(($delimiter_count-1))
  done
  new_line
}
